name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: notes
  ECS_SERVICE: NotesService
  ECS_CLUSTER: NotesCluster
  CONTAINER_NAME: notes-container

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Create task definition file
      run: |
        echo '{
          "family": "note-taking-app",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512",
          "executionRoleArn": "arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/ecsTaskExecutionRole",
          "taskRoleArn": "arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/ecsTaskRole",
          "containerDefinitions": [
            {
              "name": "notes-container",
              "image": "PLACEHOLDER_IMAGE",
              "essential": true,
              "memory": 512,
              "cpu": 256,
              "portMappings": [
                {
                  "containerPort": 8080,
                  "hostPort": 8080
                }
              ],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/note-taking-app",
                  "awslogs-region": "us-east-1",
                  "awslogs-stream-prefix": "ecs"
                }
              },
              "environment": [
                {
                  "name": "PORT",
                  "value": "8080"
                }
              ]
            }
          ]
        }' > new-task-definition.json

    - name: Register new task definition
      id: register-task-def
      run: |
        jq --arg IMAGE_URI "$IMAGE_URI" '.containerDefinitions[0].image = $IMAGE_URI' new-task-definition.json > updated-task-definition.json
        aws ecs register-task-definition \
          --cli-input-json file://updated-task-definition.json \
          --region $AWS_REGION

    - name: Deploy Amazon ECS task definition
      run: |
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition note-taking-app --region $AWS_REGION | jq -r '.taskDefinition.taskDefinitionArn')
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --task-definition $TASK_DEFINITION \
          --region $AWS_REGION \
          --force-new-deployment

